Translated into Russian
Eng1N33R/MechanicalTech pull request #3
Opened 2020-12-08 19:21 UTC by Miros77

2020-12-09 18:55 UTC, Eng1N33R requested changes
Vanilla Minecraft uses regular Russian sentence case for item names. I think this translation should follow suit.
![image](https://user-images.githubusercontent.com/4773889/101673592-6fb3db80-3a68-11eb-8cf2-3cce26d2a43f.png)

2020-12-09 18:55 UTC, Eng1N33R commented on src/main/resources/assets/mechanicaltech/lang/ru_ru.json
> +  "block.mechanicaltech.windsail": "Парусник",
This should probably be "Парус" or "Паруса", seeing as "парусник" is a sailing ship.

2020-12-09 18:55 UTC, Eng1N33R commented on src/main/resources/assets/mechanicaltech/lang/ru_ru.json
> +  "block.mechanicaltech.battery_cap": "Крышка Батареи",
Ideally, all three should have a single format - either adjective + noun, or noun + genitive noun. I think Ядро батареи and Основа батареи sound better than the current translation.

2020-12-09 18:55 UTC, Eng1N33R commented on src/main/resources/assets/mechanicaltech/lang/ru_ru.json
> +  "item.mechanicaltech.cross_connector": "Cross Connector",
Missed one.

2020-12-09 18:55 UTC, Eng1N33R commented on src/main/resources/assets/mechanicaltech/lang/ru_ru.json
> +  "block.mechanicaltech.angled_connector_right": "Угловой Соединитель (Сбоку)",
Maybe this should be "Вбок", to have them all look the same. Alternatively, they could be called нижний, верхний and боковой.

2020-12-09 21:25 UTC, Miros77 commented
Thanks, I'll try to fix it

2020-12-09 21:26 UTC, Miros77 commented on src/main/resources/assets/mechanicaltech/lang/ru_ru.json
> +  "block.mechanicaltech.angled_connector_right": "Угловой Соединитель (Сбоку)",
Yes I made a mistake here

2020-12-09 22:22 UTC, Miros77 commented
New Model for Windsail

Screenshots
![2020-12-10_01 20 35](https://user-images.githubusercontent.com/59547044/101695617-ee6b4180-3a85-11eb-8119-57076be741f6.png)

Model
[windsail.zip](https://github.com/Eng1N33R/MechanicalTech/files/5669077/windsail.zip)

2020-12-10 09:03 UTC, Eng1N33R approved these changes

2020-12-10 09:04 UTC, merged

2020-12-10 09:15 UTC, Eng1N33R commented
Thank you for your contribution! I've replaced the model, but in the future, it is best to use separate pull requests for separate contributions to keep things in order :)